services:
  # Backend service (development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: star-dog-walk-backend-dev
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=dev-secret-key
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app/server
      - /app/node_modules
    networks:
      - star-dog-walk-network
    restart: unless-stopped
    command: ["node", "--watch", "server/index.js"]

  # Frontend service (development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: star-dog-walk-frontend-dev
    environment:
      - VITE_API_URL=http://localhost:3001/api
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - star-dog-walk-network
    restart: unless-stopped

networks:
  star-dog-walk-network:
    driver: bridge
